FROM docker.bintray.io/jfrog/artifactory-pro:5.2.0
ADD https://jdbc.postgresql.org/download/postgresql-9.4.1212.jre7.jar /
RUN cp postgresql-9.4.1212.jre7.jar /opt/jfrog/artifactory/tomcat/lib/postgresql-9.4.1212.jar