version: '3'

networks:
  devnetwork:
    external: true

volumes: 
 postgres:
 data:
 extra_conf:
 nginx_conf:

services:
 postgresql:
    image: docker.bintray.io/postgres:9.5.2
    networks: 
      devnetwork:
        ipv4_address: 172.18.0.6
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=password
    volumes:
     - postgres:/var/lib/postgresql/data
    restart: always
 
 artifactory:
   build: .
   networks: 
     devnetwork:
       ipv4_address: 172.18.0.7
   container_name: artifactory
   ports:
    - 8081:8081
   depends_on:
    - postgresql
   volumes:
    - data:/var/opt/jfrog/artifactory
    - extra_conf:/artifactory_extra_conf
   environment:
    - DB_TYPE=postgresql
    # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
    - DB_USER=artifactory
    - DB_PASSWORD=password
    # Add extra Java options by uncommenting the following line
    #- EXTRA_JAVA_OPTIONS=-Xmx4g
   restart: always

 nginx:
   image: docker.bintray.io/jfrog/nginx-artifactory-pro:5.2.1
   container_name: nginx
   networks: 
      devnetwork:
        ipv4_address: 172.18.0.8
   ports:
    - 85:80
    - 443:443
   depends_on:
    - artifactory
   volumes:
    - nginx_conf:/var/opt/jfrog/nginx
   environment:
    - ART_BASE_URL=http://artifactory:8081/artifactory
    - SSL=true
   restart: always